DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
	id INT AUTO_INCREMENT PRIMARY KEY,
  	user_name VARCHAR(100) NOT NULL,
  	password VARCHAR(100) NOT NULL,
  	active BOOLEAN NOT NULL,
  	roles VARCHAR(250) NOT NULL
);